rarity_list:
  - common
  - uncommon
  - rare
  - epic
  - legendary
# НЕ МЕНЯТЬ ЛИСТ РЕДКОСТЕЙ!

damage_mod:
  common: 0
  uncommon: 2.5
  rare: 4
  epic: 4.5
  legendary: 5.2
#Ну это еще можно менять(ЦИФРЫ)

ability_translate:
  fire: "Пламенный удар"